# default model config does not override anything
#default:
#  model_kwargs: {}
#  featurize_kwargs: {}

#####################
## Main configuration

modelSharma_dataSharma:
  data_config:
    data_path: "data/modelSharma_dataSharma.csv"
    new_variant_path: "data/nuts3_new_variant_fraction.csv"
    preprocess_data_kwargs:
      start_date: "2020-08-01"
      end_date: "2021-01-22"
    mask_from_date: "2021-01-09"
  model_kwargs: {}
  featurize_kwargs: 
    drop_npi_filter:
      - {"query": "Childcare Closed", "type": "equals"}
      - {"query": "All Face-to-Face Businesses Closed", "type": "equals"}

##################################################
## Main configuration with adjustment for mobility
## (all features except parks)

modelSharma_dataSharma_countryMobility1:
  data_config:
    data_path: "data/modelSharma_dataSharma_countryMobility_RecreGrocTransWorkResid.csv"
    new_variant_path: "data/nuts3_new_variant_fraction.csv"
    preprocess_data_kwargs:
      start_date: "2020-08-01"
      end_date: "2021-01-22"
    mask_from_date: "2021-01-09"
  model_kwargs: {}
  featurize_kwargs: 
    drop_npi_filter:
      - {"query": "Childcare Closed", "type": "equals"}
      - {"query": "All Face-to-Face Businesses Closed", "type": "equals"}
